### PR TITLE
Add fuzz tests for ASE

### PR DESCRIPTION
**Pull request by sophimao**
Fuzz the following interfaces:
* ASE scripts
  * afu_sim_setup
* ASE config and script files
  * ase.cfg
  * ase_regress.sh
* ASE environment variables
  * LIBFPGA_LOG and ASE_LOG
  * ASE_WORKDIR
  * ASE_CONFIG
  * ASE_SCRIPT

Other than the ASE script test, the rest runs an example design, added in the samples directory, in ASE with the interface under test fuzzed using Radamsa.

### CODE REVIEW

**Review by michael-adler — COMMENTED** [review]
Instead of copying hello_world, have your script clone the examples repo and compile the cloned example. That way we don't have to maintain a copy of the workload.

Can't something similar be done with the test scripts? Why should there be a copy of the same test scripts in every repo?

**Comment by sophimao** [comment]
> Instead of copying hello_world, have your script clone the examples repo and compile the cloned example. That way we don't have to maintain a copy of the workload.

I can look into this.

> Can't something similar be done with the test scripts? Why should there be a copy of the same test scripts in every repo?

Do you mean we should have a separate repo for the test scripts I added in this PR?

**Comment by michael-adler** [comment]
> Do you mean we should have a separate repo for the test scripts I added in this PR?

Yes. Why copy the same script to multiple repos and leave yourself with yet another maintenance headache when a single fuzz tester could be applied to a collection of repos? Of course some parameters would have to be defined that are repo-specific, but not the whole tester. This is the UVM/unit test replication mistake repeated.

**Comment by sophimao** [comment]
Moving this to a new repo.

**Pull request closed without merging**
